module.exports = [
  {
    Name: "Cleaver",
    Type: "Blade",
    "Unlock Prerequisite": "",
    "Research Scrolls": "",
    Tier: 1,
    Value: 80,
    "Crafting Time (seconds)": 15,
    "Crafting Time (formatted)": "0:00:15",
    "Value / Crafting Time": 5.33,
    "Merchant XP": 2,
    "Merchant XP / Crafting Time": 0.13,
    "Worker XP": 2,
    "Required Worker": "Blacksmith",
    "Worker Level": 1,
    "Required Worker__1": "---",
    "Worker Level__1": "---",
    iron: 1,
    wood: "",
    leather: "",
    herbs: "",
    steel: "",
    ironwood: "",
    fabric: "",
    oil: "",
    mana: "",
    gems: "",
    Component: "---",
    "Component Quality": "",
    "Amount Needed": "",
    Component__1: "---",
    "Component Quality__1": "",
    "Amount Needed__1": "",
    ATK: 16,
    DEF: 0,
    HP: 0,
    "Crafting Upgrade 1": "Blueprint: Shiv",
    "Crafts Needed": 7,
    "Crafting Upgrade 2": "Blueprint: Arming Sword",
    "Crafts Needed__1": 18,
    "Crafting Upgrade 3": "x1.5 Value Increase",
    "Crafts Needed__2": 32,
    "Crafting Upgrade 4": "Quality Chance x2",
    "Crafts Needed__3": 50,
    "Crafting Upgrade 5": "Quality Chance x3",
    "Crafts Needed__4": 80,
    "Ascension Upgrade 1": "-4 Iron Spent",
    "Shards Needed": 5,
    "Ascension Upgrade 2": "+30% Critical Craft Chance",
    "Shards Needed__1": 5,
    "Ascension Upgrade 3": "Quality Chance x3",
    "Shards Needed__2": 5,
    "Discount Energy": 5,
    "Surcharge Energy": 15,
    "Suggest Energy": 5,
    "Speed Up Energy": 15,
  },
]
